name: Despliegue Autom√°tico JCMC

on:
  push:
    branches:
      - main  # <-- Verifica si tu rama principal se llama 'main' o 'master'

jobs:
  web-deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: üöö Obteniendo el c√≥digo m√°s reciente
      uses: actions/checkout@v3

    - name: üìÇ Subiendo archivos a Hostinger v√≠a FTP
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        # Excluimos lo que no queremos que se sobreescriba o sea basura
        exclude: |
          **/.git*
          **/node_modules/**
          **/vendor/**
          .env
          storage/-
          bootstrap/cache/-